### ISSUE TITLE
keep raw images (Windows)

### ISSUE THREAD

**Issue by schneich** [haverland/collectmeterdigits#16]
Hi,

I changed some settings on my AI-on-the-Edge-Device a couple of hours ago. Now, I would like to start labelling the images, but only on the images that are based on the new settings.

I am working on Windows and I use this command to collect the images from my device:
`collectmeterdigits.exe --collect=192.168.30.18 --days=1 --keepdownloads`

After the download finishes, all files are renamed and moved to the folder **labeled**. There is still a folder structure for the raw images, but it's all empty.

The above code downloads all the images from today, but it does not keep the raw images. What am I doing wrong? Or is this a bug in the windows version of the tool? (I have downloaded the tool at 12.7.2023 - not sure, what version that is..)

Thank you for your feedback,
Chris

**Comment by schneich** [comment]
Hi,

my work around: I access the device via GUI and delete the not needed images on the device.

`System -> File Server -> ...`

It would be faster and more convenient, if one could sort it in Windows... :-)

**Comment by haverland** [comment]
Thanks for describing the issue. Looks like the option will not used correctly in all versions, not only windows.
